# Generated by Django 2.1.7 on 2019-04-24 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Afiliacao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('sigla', models.CharField(max_length=100)),
                ('cidade', models.CharField(max_length=200)),
                ('estado', models.CharField(max_length=200)),
                ('pais', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Anais',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('isbn', models.CharField(max_length=17)),
                ('data_de_publicacao', models.DateField()),
                ('pais_de_publicacao', models.CharField(max_length=100)),
                ('idioma_de_publicacao', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='AreaTematica',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Autor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_para_citacao', models.CharField(max_length=100)),
                ('contato', models.EmailField(max_length=254)),
                ('afiliacao', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='autores', to='anais.Afiliacao')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('local', models.CharField(max_length=200)),
                ('apresentação', models.TextField()),
                ('comissao_organizadora', models.TextField()),
                ('comissao_cientifica', models.TextField()),
                ('contato', models.CharField(max_length=200)),
                ('icone', models.ImageField(upload_to='images/')),
                ('banner', models.ImageField(upload_to='images/')),
                ('anais', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='anais.Anais')),
                ('areas_tematicas', models.ManyToManyField(to='anais.AreaTematica')),
                ('edicao_anterior', models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, to='anais.Evento')),
            ],
        ),
        migrations.CreateModel(
            name='Modalidade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Trabalho',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200, null=True)),
                ('pdf', models.FileField(upload_to='uploads/%Y/')),
                ('anais', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='anais.Anais')),
                ('area_tematica', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='anais.AreaTematica')),
                ('autores', models.ManyToManyField(to='anais.Autor')),
                ('modalidade', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trabalhos', to='anais.Modalidade')),
            ],
        ),
    ]
