# Generated by Django 2.2 on 2019-04-25 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anais', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evento',
            name='slug',
            field=models.SlugField(editable=False, unique=True),
        ),
    ]
