# Generated by Django 2.2 on 2019-04-24 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('anais', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='afiliacao',
            options={'verbose_name': 'afiliação', 'verbose_name_plural': 'afiliações'},
        ),
        migrations.AlterModelOptions(
            name='anais',
            options={'verbose_name_plural': 'anais'},
        ),
        migrations.AlterModelOptions(
            name='areatematica',
            options={'verbose_name': 'área temática', 'verbose_name_plural': 'áreas temáticas'},
        ),
        migrations.AlterModelOptions(
            name='autor',
            options={'ordering': ['afiliacao', 'nome'], 'verbose_name_plural': 'autores'},
        ),
    ]
