# Generated by Django 2.2 on 2019-04-26 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('anais', '0002_auto_20190425_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='trabalho',
            name='slug',
            field=models.SlugField(editable=False, null=True, unique=True),
        ),
    ]
